config/routes.rb
Cml::Application.routes.draw do
	root to: 'pages#home'

  get '/register', to: 'users#new', as: 'register'
  resources :users, only: ['create']

  get '/login', to: 'sessions#new', as: 'login'
  resources :sessions, only: ['create', 'destroy']
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :init

  def new
    @user = @user_repository.create
  end

  def create
    @login_service.login(params[:user])
  end

  def login_succeeded(message)
    redirect_to root_path, notice: message
  end

  def login_failed(user, message)
    @user = user
    flash[:notice] = message
    render :new
  end

  private

  def init
    @user_repository = UserRepository.new
    @login_service = LoginService.new(self, @user_repository)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :init

  def new
    @user = @user_repository.create
  end

  def create
    @registration_service.register(params[:user])
  end

  def create_succeeded(user, message)
    redirect_to root_path, notice: message
  end

  def create_failed(user, message)
    @user = user
    flash[:notice] = message
    render :new
  end

  private

  def init
    @user_repository = UserRepository.new
    @registration_service = RegistrationService.new(self, @user_repository)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatMeetLove.com</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header>
    <ul class="list-inline">
      <li><%= link_to 'home', root_path %></li>
      <li><%= link_to 'login', login_path %></li>
      <li><%= link_to 'register', register_path %></li>
    </ul>
  </header>

  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-info #{key}" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<%= form_for :user, url: users_path, html: { role: 'form' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, required: true, class: 'form-control' %>
  </div class="form-group">
  
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Sign up', class: 'btn' %>
  </div>
<% end %>